import type { OnModMailRequest } from '@devvit/web/shared';
import { context, reddit, redis, settings } from '@devvit/web/server';

export const MODMAIL_SPAM_CLOSER_REASON =
  'Modmail spam closer: automated appeal or spam conversation';

export const MODMAIL_SPAM_CLOSER_ENABLED_SETTING = 'modmailSpamCloserEnabled';

const DAY_IN_MS = 24 * 60 * 60 * 1000;
const CLOSE_DEDUPE_TTL_DAYS = 30;

type ModmailSpamCloserResult = {
  status: 'closed' | 'skipped' | 'error';
  reason: string;
  conversationId?: string;
};

type ModmailConversationResponse = Awaited<
  ReturnType<typeof reddit.modMail.getConversation>
>;
type LoadedConversation = NonNullable<ModmailConversationResponse['conversation']>;
type LoadedMessage = LoadedConversation['messages'][string];
type LoadedUser = ModmailConversationResponse['user'];

type ModmailReviewInput = {
  subject: string;
  participantText: string;
  conversationState: string;
  isAutoGenerated: boolean;
  user?: LoadedUser;
};

const SPAM_SIGNAL_PATTERNS = [
  /\b(?:telegram|whatsapp|signal)\b/iu,
  /\b(?:crypto|bitcoin|forex|investment|binary options?)\b/iu,
  /\b(?:recovery|hack(?:ed)?|hacker)\s+(?:service|expert|agent)\b/iu,
  /\b(?:onlyfans|fansly|snapchat premium)\b/iu,
  /\b(?:seo|guest post|backlinks?|sponsored post)\b/iu,
  /\b(?:discord\.gg|t\.me\/|wa\.me\/)\b/iu,
  /\b(?:buy|sell)\s+(?:account|upvotes?|karma|subscribers?)\b/iu,
  /\b(?:cheap|guaranteed)\s+(?:traffic|followers|subscribers?)\b/iu,
];

const BOT_APPEAL_PATTERNS = [
  /\bappeal(?:ing)?\b.{0,80}\b(?:bot|spam|shadow\s?ban|suspended)\b/isu,
  /\b(?:bot|spam|shadow\s?ban|suspended)\b.{0,80}\bappeal(?:ing)?\b/isu,
  /\b(?:i am|i'm|im)\s+not\s+(?:a\s+)?bot\b/iu,
  /\bmistakenly\s+(?:flagged|marked|banned|suspended)\b/iu,
  /\bplease\s+(?:unban|approve|restore)\s+(?:my\s+)?account\b/iu,
];

const isModmailSpamCloserEnabled = async () => {
  const value = await settings.get(MODMAIL_SPAM_CLOSER_ENABLED_SETTING);

  return typeof value === 'boolean' ? value : true;
};

const normalizeState = (state: string) => state.toLowerCase().replace(/[_\s-]/gu, '');

const getMessageBody = (message: LoadedMessage) =>
  [message.bodyMarkdown, message.body].filter(Boolean).join('\n');

const getParticipantMessages = (conversation: LoadedConversation) =>
  Object.values(conversation.messages)
    .filter((message) => !message.isInternal && !message.author?.isMod)
    .map(getMessageBody)
    .filter(Boolean);

const matchesAny = (text: string, patterns: RegExp[]) =>
  patterns.some((pattern) => pattern.test(text));

export const reviewModmailSpam = ({
  subject,
  participantText,
  conversationState,
  isAutoGenerated,
  user,
}: ModmailReviewInput) => {
  const combinedText = `${subject}\n${participantText}`.trim();
  const normalizedState = normalizeState(conversationState);

  if (!combinedText) {
    return {
      shouldClose: false,
      reason: 'conversation has no reviewable participant text',
    };
  }

  if (normalizedState === 'appeals' && user?.isShadowBanned) {
    return {
      shouldClose: true,
      reason: 'appeal from shadowbanned account',
    };
  }

  if (normalizedState === 'appeals' && user?.isSuspended) {
    return {
      shouldClose: true,
      reason: 'appeal from suspended account',
    };
  }

  if (
    normalizedState === 'appeals' &&
    isAutoGenerated &&
    matchesAny(combinedText, BOT_APPEAL_PATTERNS)
  ) {
    return {
      shouldClose: true,
      reason: 'automated bot or spam appeal',
    };
  }

  if (matchesAny(combinedText, SPAM_SIGNAL_PATTERNS)) {
    return {
      shouldClose: true,
      reason: 'matched modmail spam signal',
    };
  }

  return {
    shouldClose: false,
    reason: 'no modmail spam signal matched',
  };
};

const closeConversation = async (conversationId: string, reason: string) => {
  const dedupeKey = `modmail-spam-closer:closed:${conversationId}`;
  const alreadyClosed = await redis.get(dedupeKey);

  if (alreadyClosed) {
    return {
      status: 'skipped',
      reason: 'conversation was already closed by modmail spam closer',
      conversationId,
    } satisfies ModmailSpamCloserResult;
  }

  await reddit.modMail.reply({
    conversationId,
    body: `${MODMAIL_SPAM_CLOSER_REASON}: ${reason}`,
    isInternal: true,
    isAuthorHidden: true,
  });
  await reddit.modMail.archiveConversation(conversationId);

  const expiration = new Date(Date.now() + CLOSE_DEDUPE_TTL_DAYS * DAY_IN_MS);

  await redis.set(dedupeKey, reason, { expiration });

  return {
    status: 'closed',
    reason,
    conversationId,
  } satisfies ModmailSpamCloserResult;
};

export const handleModmailSpamCloser = async (
  input: OnModMailRequest
): Promise<ModmailSpamCloserResult> => {
  if (!(await isModmailSpamCloserEnabled())) {
    return {
      status: 'skipped',
      reason: 'modmail spam closer is disabled for this subreddit',
    };
  }

  if (!context.subredditName) {
    return {
      status: 'skipped',
      reason: 'subreddit context is unavailable',
    };
  }

  if (!input.conversationId) {
    return {
      status: 'skipped',
      reason: 'modmail event did not include a conversation id',
    };
  }

  if (input.messageAuthorType !== 'participant_user') {
    return {
      status: 'skipped',
      reason: 'latest modmail message was not from a user participant',
      conversationId: input.conversationId,
    };
  }

  if (input.conversationType !== 'sr_user') {
    return {
      status: 'skipped',
      reason: 'conversation is not a subreddit-to-user modmail thread',
      conversationId: input.conversationId,
    };
  }

  if (normalizeState(input.conversationState) === 'archived') {
    return {
      status: 'skipped',
      reason: 'conversation is already archived',
      conversationId: input.conversationId,
    };
  }

  try {
    const { conversation, user } = await reddit.modMail.getConversation({
      conversationId: input.conversationId,
      markRead: true,
    });

    if (!conversation) {
      return {
        status: 'skipped',
        reason: 'modmail conversation could not be loaded',
        conversationId: input.conversationId,
      };
    }

    const review = reviewModmailSpam({
      subject: conversation.subject ?? '',
      participantText: getParticipantMessages(conversation).join('\n\n'),
      conversationState: input.conversationState,
      isAutoGenerated: input.isAutoGenerated,
      user,
    });

    if (!review.shouldClose) {
      return {
        status: 'skipped',
        reason: review.reason,
        conversationId: input.conversationId,
      };
    }

    return await closeConversation(input.conversationId, review.reason);
  } catch (error) {
    console.error(`Error processing modmail spam closer: ${error}`);

    return {
      status: 'error',
      reason: 'failed to process modmail spam closer',
      conversationId: input.conversationId,
    };
  }
};
